//Written by: Karol Josef Bustamante
//API's used: CraftyJS

//cards parsed in javascript as craftyJS sprites
Crafty.sprite("feelingsBack/feeling_back_faded.png", {feeling_back_faded: [0, 0, 1000, 1000]});
Crafty.sprite("needsBack/need_back_faded.png", {need_back_faded: [0, 0, 1000, 1000]});
Crafty.sprite("feelingsBack/feeling_back.png", {feeling_back: [0, 0, 1000, 1000]});
Crafty.sprite("needsBack/need_back.png", {need_back: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-01.png", {needs1: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-01.png", {feelings1: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-02.png", {needs2: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-03.png", {needs3: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-03.png", {feelings3: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-04.png", {needs4: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-05.png", {needs5: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-05.png", {feelings5: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-06.png", {needs6: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-06.png", {feelings6: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-07.png", {needs7: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-07.png", {feelings7: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-08.png", {needs8: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-08.png", {feelings8: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-09.png", {needs9: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-10.png", {needs10: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-10.png", {feelings10: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-11.png", {needs11: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-11.png", {feelings11: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-12.png", {needs12: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-12.png", {feelings12: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-13.png", {needs13: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-13.png", {feelings13: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-14.png", {needs14: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-14.png", {feelings14: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-15.png", {needs15: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-15.png", {feelings15: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-16.png", {needs16: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-16.png", {feelings16: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-17.png", {needs17: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-18.png", {needs18: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-18.png", {feelings18: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-19.png", {needs19: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-19.png", {feelings19: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-20.png", {needs20: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-20.png", {feelings20: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-21.png", {needs21: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-21.png", {feelings21: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-22.png", {needs22: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-22.png", {feelings22: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-23.png", {needs23: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-23.png", {feelings23: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-24.png", {needs24: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-24.png", {feelings24: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-25.png", {needs25: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-25.png", {feelings25: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-26.png", {needs26: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-26.png", {feelings26: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-27.png", {needs27: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-27.png", {feelings27: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-28.png", {needs28: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-28.png", {feelings28: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-29.png", {needs29: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-29.png", {feelings29: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-30.png", {needs30: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-31.png", {needs31: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-31.png", {feelings31: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-32.png", {needs32: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-32.png", {feelings32: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-33.png", {needs33: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-33.png", {feelings33: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-34.png", {needs34: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-35.png", {needs35: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-35.png", {feelings35: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-36.png", {needs36: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-36.png", {feelings36: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-37.png", {needs37: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-37.png", {feelings37: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-38.png", {needs38: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-38.png", {feelings38: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-39.png", {needs39: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-39.png", {feelings39: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-40.png", {needs40: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-40.png", {feelings40: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-41.png", {needs41: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-41.png", {feelings41: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-42.png", {needs42: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-43.png", {needs43: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-43.png", {feelings43: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-44.png", {needs44: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-44.png", {feelings44: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-45.png", {needs45: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-45.png", {feelings45: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-46.png", {needs46: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-46.png", {feelings46: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-47.png", {needs47: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-47.png", {feelings47: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-48.png", {needs48: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-48.png", {feelings48: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-49.png", {needs49: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-49.png", {feelings49: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-50.png", {needs50: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-51.png", {needs51: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-52.png", {needs52: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-52.png", {feelings52: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-53.png", {needs53: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-53.png", {feelings53: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-54.png", {needs54: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-55.png", {needs55: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-56.png", {needs56: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-57.png", {needs57: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-58.png", {needs58: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-59.png", {needs59: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-60.png", {needs60: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-60.png", {feelings60: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-61.png", {needs61: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-62.png", {needs62: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-62.png", {feelings62: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-63.png", {needs63: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-64.png", {needs64: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-64.png", {feelings64: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-65.png", {needs65: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-66.png", {needs66: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-67.png", {needs67: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-68.png", {needs68: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-69.png", {needs69: [0, 0, 1000, 1000]});
Crafty.sprite("needs/Cards Needs final-70.png", {needs70: [0, 0, 1000, 1000]});
Crafty.sprite("feelings/Cards Feelings final-70.png", {feelings70: [0, 0, 1000, 1000]});
Crafty.sprite("save-button.png", {saveButton: [0, 0, 1000, 1000]});
Crafty.sprite("load-button.png", {loadButton: [0, 0, 1000, 1000]});

//The stacks that will represent the feelings and needs decks
var stackF = [];
var stackN = [];
//second set of stacks in order to keep track of cards in the field
var onTopPickPileN = [];
var onTopPickPileF = [];

var cardWidth = 100;
var cardHeight = 100;
var dragging = false;

//make the back and faded back cards into craftyJS entities
var imgFB = Crafty.e("2D, DOM, feeling_back, Mouse").attr({x:0, y:0, w:0,h: 0});
var imgNB = Crafty.e("2D, DOM, need_back, Mouse").attr({x:0, y:0, w:0,h: 0});
var imgFBFaded = Crafty.e("2D, DOM, feeling_back_faded, Blocks, Collision, Mouse").attr({x:0, y:0, w:0,h: 0});
var imgNBFaded = Crafty.e("2D, DOM, need_back_faded, Blocks,Collision, Mouse").attr({x:0, y:0, w:0,h: 0});

//make the cards into craftyJS entities
var img1 = Crafty.e("2D, DOM, needs1, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img1);
var img2 = Crafty.e("2D, DOM, feelings1, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img2);
var img3 = Crafty.e("2D, DOM, needs2, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img3);
var img5 = Crafty.e("2D, DOM, needs3, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img5);
var img6 = Crafty.e("2D, DOM, feelings3, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img6);
var img7 = Crafty.e("2D, DOM, needs4, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img7);
var img9 = Crafty.e("2D, DOM, needs5, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img9);
var img10 = Crafty.e("2D, DOM, feelings5, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img10);
var img11 = Crafty.e("2D, DOM, needs6, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img11);
var img12 = Crafty.e("2D, DOM, feelings6, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img12);
var img13 = Crafty.e("2D, DOM, needs7, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img13);
var img14 = Crafty.e("2D, DOM, feelings7, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img14);
var img15 = Crafty.e("2D, DOM, needs8, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img15);
var img16 = Crafty.e("2D, DOM, feelings8, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img16);
var img17 = Crafty.e("2D, DOM, needs9, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img17);
var img19 = Crafty.e("2D, DOM, needs10, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img19);
var img20 = Crafty.e("2D, DOM, feelings10, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img20);
var img21 = Crafty.e("2D, DOM, needs11, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img21);
var img22 = Crafty.e("2D, DOM, feelings11, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img22);
var img23 = Crafty.e("2D, DOM, needs12, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img23);
var img24 = Crafty.e("2D, DOM, feelings12, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img24);
var img25 = Crafty.e("2D, DOM, needs13, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img25);
var img26 = Crafty.e("2D, DOM, feelings13, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img26);
var img27 = Crafty.e("2D, DOM, needs14, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img27);
var img28 = Crafty.e("2D, DOM, feelings14, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img28);
var img29 = Crafty.e("2D, DOM, needs15, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img29);
var img30 = Crafty.e("2D, DOM, feelings15, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img30);
var img31 = Crafty.e("2D, DOM, needs16, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img31);
var img32 = Crafty.e("2D, DOM, feelings16, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img32);
var img33 = Crafty.e("2D, DOM, needs17, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img33);
var img35 = Crafty.e("2D, DOM, needs18, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img35);
var img36 = Crafty.e("2D, DOM, feelings18, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img36);
var img37 = Crafty.e("2D, DOM, needs19, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img37);
var img38 = Crafty.e("2D, DOM, feelings19, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img38);
var img39 = Crafty.e("2D, DOM, needs20, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img39);
var img40 = Crafty.e("2D, DOM, feelings20, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img40);
var img41 = Crafty.e("2D, DOM, needs21, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img41);
var img42 = Crafty.e("2D, DOM, feelings21, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img42);
var img43 = Crafty.e("2D, DOM, needs22, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img43);
var img44 = Crafty.e("2D, DOM, feelings22, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img44);
var img45 = Crafty.e("2D, DOM, needs23, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img45);
var img46 = Crafty.e("2D, DOM, feelings23, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img46);
var img47 = Crafty.e("2D, DOM, needs24, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img47);
var img48 = Crafty.e("2D, DOM, feelings24, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img48);
var img49 = Crafty.e("2D, DOM, needs25, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img49);
var img50 = Crafty.e("2D, DOM, feelings25, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img50);
var img51 = Crafty.e("2D, DOM, needs26, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img51);
var img52 = Crafty.e("2D, DOM, feelings26, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img52);
var img53 = Crafty.e("2D, DOM, needs27, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img53);
var img54 = Crafty.e("2D, DOM, feelings27, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img54);
var img55 = Crafty.e("2D, DOM, needs28, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img55);
var img56 = Crafty.e("2D, DOM, feelings28, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img56);
var img57 = Crafty.e("2D, DOM, needs29, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img57);
var img58 = Crafty.e("2D, DOM, feelings29, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img58);
var img59 = Crafty.e("2D, DOM, needs30, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img59);
var img61 = Crafty.e("2D, DOM, needs31, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img61);
var img62 = Crafty.e("2D, DOM, feelings31, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img62);
var img63 = Crafty.e("2D, DOM, needs32, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img63);
var img64 = Crafty.e("2D, DOM, feelings32, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img64);
var img65 = Crafty.e("2D, DOM, needs33, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img65);
var img66 = Crafty.e("2D, DOM, feelings33, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img66);
var img67 = Crafty.e("2D, DOM, needs34, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img67);
var img69 = Crafty.e("2D, DOM, needs35, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img69);
var img70 = Crafty.e("2D, DOM, feelings35, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img70);
var img71 = Crafty.e("2D, DOM, needs36, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img71);
var img72 = Crafty.e("2D, DOM, feelings36, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img72);
var img73 = Crafty.e("2D, DOM, needs37, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img73);
var img74 = Crafty.e("2D, DOM, feelings37, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img74);
var img75 = Crafty.e("2D, DOM, needs38, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img75);
var img76 = Crafty.e("2D, DOM, feelings38, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img76);
var img77 = Crafty.e("2D, DOM, needs39, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img77);
var img78 = Crafty.e("2D, DOM, feelings39, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img78);
var img79 = Crafty.e("2D, DOM, needs40, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img79);
var img80 = Crafty.e("2D, DOM, feelings40, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img80);
var img81 = Crafty.e("2D, DOM, needs41, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img81);
var img82 = Crafty.e("2D, DOM, feelings41, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img82);
var img83 = Crafty.e("2D, DOM, needs42, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img83);
var img85 = Crafty.e("2D, DOM, needs43, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img85);
var img86 = Crafty.e("2D, DOM, feelings43, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img86);
var img87 = Crafty.e("2D, DOM, needs44, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img87);
var img88 = Crafty.e("2D, DOM, feelings44, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img88);
var img89 = Crafty.e("2D, DOM, needs45, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img89);
var img90 = Crafty.e("2D, DOM, feelings45, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img90);
var img91 = Crafty.e("2D, DOM, needs46, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img91);
var img92 = Crafty.e("2D, DOM, feelings46, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img92);
var img93 = Crafty.e("2D, DOM, needs47, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img93);
var img94 = Crafty.e("2D, DOM, feelings47, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img94);
var img95 = Crafty.e("2D, DOM, needs48, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img95);
var img96 = Crafty.e("2D, DOM, feelings48, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img96);
var img97 = Crafty.e("2D, DOM, needs49, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img97);
var img98 = Crafty.e("2D, DOM, feelings49, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img98);
var img99 = Crafty.e("2D, DOM, needs50, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img99);
var img101 = Crafty.e("2D, DOM, needs51, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img101);
var img103 = Crafty.e("2D, DOM, needs52, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img103);
var img104 = Crafty.e("2D, DOM, feelings52, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img104);
var img105 = Crafty.e("2D, DOM, needs53, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img105);
var img106 = Crafty.e("2D, DOM, feelings53, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img106);
var img107 = Crafty.e("2D, DOM, needs54, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img107);
var img109 = Crafty.e("2D, DOM, needs55, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img109);
var img111 = Crafty.e("2D, DOM, needs56, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img111);
var img113 = Crafty.e("2D, DOM, needs57, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img113);
var img115 = Crafty.e("2D, DOM, needs58, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img115);
var img117 = Crafty.e("2D, DOM, needs59, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img117);
var img119 = Crafty.e("2D, DOM, needs60, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img119);
var img120 = Crafty.e("2D, DOM, feelings60, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img120);
var img121 = Crafty.e("2D, DOM, needs61, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img121);
var img123 = Crafty.e("2D, DOM, needs62, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img123);
var img124 = Crafty.e("2D, DOM, feelings62, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img124);
var img125 = Crafty.e("2D, DOM, needs63, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img125);
var img127 = Crafty.e("2D, DOM, needs64, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img127);
var img128 = Crafty.e("2D, DOM, feelings64, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackN.push(img128);
var img129 = Crafty.e("2D, DOM, needs65, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img129);
var img131 = Crafty.e("2D, DOM, needs66, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img131);
var img133 = Crafty.e("2D, DOM, needs67, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img133);
var img135 = Crafty.e("2D, DOM, needs68, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img135);
var img137 = Crafty.e("2D, DOM, needs69, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img137);
var img139 = Crafty.e("2D, DOM, needs70, Collision , Draggable").attr({x:0, y:0, w:0,h: 0});
stackF.push(img139);
var img140 = Crafty.e("2D, DOM, feelings70, Collision , Draggable").attr({x:0, y:0, w:0,h:0});
stackN.push(img140);

var saveB = Crafty.e("2D, DOM, saveButton, Collision, Mouse").attr({x:350, y:0, w:100,h: 100});
var loadB = Crafty.e("2D, DOM, loadButton, Collision, Mouse").attr({x:350, y:40, w:100,h: 100});

//save and load template. Must implement for ALL the cards (the deck too)
//save button (save all variables to a file here)
saveB.bind("Click", function(e){
	if(typeof(Storage) !== "undefined") {
	    // Code for localStorage/sessionStorage.
		
		// Store
		//store what's on the field
		var imgx = img1.x.toString();
		var imgy = img1.y.toString();
		var imgw = img1.w.toString();
		var imgh = img1.h.toString();
		var coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img1",coordinateValue);
		imgx = img2.x.toString();
		imgy = img2.y.toString();
		imgw = img2.w.toString();
		imgh = img2.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img2",coordinateValue);
		imgx = img3.x.toString();
		imgy = img3.y.toString();
		imgw = img3.w.toString();
		imgh = img3.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img3",coordinateValue);
		imgx = img4.x.toString();
		imgy = img4.y.toString();
		imgw = img4.w.toString();
		imgh = img4.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img4",coordinateValue);
		imgx = img5.x.toString();
		imgy = img5.y.toString();
		imgw = img5.w.toString();
		imgh = img5.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img5",coordinateValue);
		imgx = img6.x.toString();
		imgy = img6.y.toString();
		imgw = img6.w.toString();
		imgh = img6.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img6",coordinateValue);
		imgx = img7.x.toString();
		imgy = img7.y.toString();
		imgw = img7.w.toString();
		imgh = img7.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img7",coordinateValue);
		imgx = img8.x.toString();
		imgy = img8.y.toString();
		imgw = img8.w.toString();
		imgh = img8.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img8",coordinateValue);
		imgx = img9.x.toString();
		imgy = img9.y.toString();
		imgw = img9.w.toString();
		imgh = img9.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img9",coordinateValue);
		imgx = img10.x.toString();
		imgy = img10.y.toString();
		imgw = img10.w.toString();
		imgh = img10.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img10",coordinateValue);
		imgx = img11.x.toString();
		imgy = img11.y.toString();
		imgw = img11.w.toString();
		imgh = img11.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img11",coordinateValue);
		imgx = img12.x.toString();
		imgy = img12.y.toString();
		imgw = img12.w.toString();
		imgh = img12.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img12",coordinateValue);
		imgx = img13.x.toString();
		imgy = img13.y.toString();
		imgw = img13.w.toString();
		imgh = img13.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img13",coordinateValue);
		imgx = img14.x.toString();
		imgy = img14.y.toString();
		imgw = img14.w.toString();
		imgh = img14.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img14",coordinateValue);
		imgx = img15.x.toString();
		imgy = img15.y.toString();
		imgw = img15.w.toString();
		imgh = img15.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img15",coordinateValue);
		imgx = img16.x.toString();
		imgy = img16.y.toString();
		imgw = img16.w.toString();
		imgh = img16.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img16",coordinateValue);
		imgx = img17.x.toString();
		imgy = img17.y.toString();
		imgw = img17.w.toString();
		imgh = img17.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img17",coordinateValue);
		imgx = img18.x.toString();
		imgy = img18.y.toString();
		imgw = img18.w.toString();
		imgh = img18.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img18",coordinateValue);
		imgx = img19.x.toString();
		imgy = img19.y.toString();
		imgw = img19.w.toString();
		imgh = img19.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img19",coordinateValue);
		imgx = img20.x.toString();
		imgy = img20.y.toString();
		imgw = img20.w.toString();
		imgh = img20.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img20",coordinateValue);
		imgx = img21.x.toString();
		imgy = img21.y.toString();
		imgw = img21.w.toString();
		imgh = img21.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img21",coordinateValue);
		imgx = img22.x.toString();
		imgy = img22.y.toString();
		imgw = img22.w.toString();
		imgh = img22.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img22",coordinateValue);
		imgx = img23.x.toString();
		imgy = img23.y.toString();
		imgw = img23.w.toString();
		imgh = img23.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img23",coordinateValue);
		imgx = img24.x.toString();
		imgy = img24.y.toString();
		imgw = img24.w.toString();
		imgh = img24.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img24",coordinateValue);
		imgx = img25.x.toString();
		imgy = img25.y.toString();
		imgw = img25.w.toString();
		imgh = img25.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img25",coordinateValue);
		imgx = img26.x.toString();
		imgy = img26.y.toString();
		imgw = img26.w.toString();
		imgh = img26.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img26",coordinateValue);
		imgx = img27.x.toString();
		imgy = img27.y.toString();
		imgw = img27.w.toString();
		imgh = img27.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img27",coordinateValue);
		imgx = img28.x.toString();
		imgy = img28.y.toString();
		imgw = img28.w.toString();
		imgh = img28.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img28",coordinateValue);
		imgx = img29.x.toString();
		imgy = img29.y.toString();
		imgw = img29.w.toString();
		imgh = img29.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img29",coordinateValue);
		imgx = img30.x.toString();
		imgy = img30.y.toString();
		imgw = img30.w.toString();
		imgh = img30.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img30",coordinateValue);
		imgx = img31.x.toString();
		imgy = img31.y.toString();
		imgw = img31.w.toString();
		imgh = img31.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img31",coordinateValue);
		imgx = img32.x.toString();
		imgy = img32.y.toString();
		imgw = img32.w.toString();
		imgh = img32.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img32",coordinateValue);
		imgx = img33.x.toString();
		imgy = img33.y.toString();
		imgw = img33.w.toString();
		imgh = img33.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img33",coordinateValue);
		imgx = img34.x.toString();
		imgy = img34.y.toString();
		imgw = img34.w.toString();
		imgh = img34.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img34",coordinateValue);
		imgx = img35.x.toString();
		imgy = img35.y.toString();
		imgw = img35.w.toString();
		imgh = img35.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img35",coordinateValue);
		imgx = img36.x.toString();
		imgy = img36.y.toString();
		imgw = img36.w.toString();
		imgh = img36.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img36",coordinateValue);
		imgx = img37.x.toString();
		imgy = img37.y.toString();
		imgw = img37.w.toString();
		imgh = img37.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img37",coordinateValue);
		imgx = img38.x.toString();
		imgy = img38.y.toString();
		imgw = img38.w.toString();
		imgh = img38.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img38",coordinateValue);
		imgx = img39.x.toString();
		imgy = img39.y.toString();
		imgw = img39.w.toString();
		imgh = img39.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img39",coordinateValue);
		imgx = img40.x.toString();
		imgy = img40.y.toString();
		imgw = img40.w.toString();
		imgh = img40.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img40",coordinateValue);
		imgx = img41.x.toString();
		imgy = img41.y.toString();
		imgw = img41.w.toString();
		imgh = img41.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img41",coordinateValue);
		imgx = img42.x.toString();
		imgy = img42.y.toString();
		imgw = img42.w.toString();
		imgh = img42.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img42",coordinateValue);
		imgx = img43.x.toString();
		imgy = img43.y.toString();
		imgw = img43.w.toString();
		imgh = img43.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img43",coordinateValue);
		imgx = img44.x.toString();
		imgy = img44.y.toString();
		imgw = img44.w.toString();
		imgh = img44.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img44",coordinateValue);
		imgx = img45.x.toString();
		imgy = img45.y.toString();
		imgw = img45.w.toString();
		imgh = img45.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img45",coordinateValue);
		imgx = img46.x.toString();
		imgy = img46.y.toString();
		imgw = img46.w.toString();
		imgh = img46.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img46",coordinateValue);
		imgx = img47.x.toString();
		imgy = img47.y.toString();
		imgw = img47.w.toString();
		imgh = img47.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img47",coordinateValue);
		imgx = img48.x.toString();
		imgy = img48.y.toString();
		imgw = img48.w.toString();
		imgh = img48.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img48",coordinateValue);
		imgx = img49.x.toString();
		imgy = img49.y.toString();
		imgw = img49.w.toString();
		imgh = img49.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img49",coordinateValue);
		imgx = img50.x.toString();
		imgy = img50.y.toString();
		imgw = img50.w.toString();
		imgh = img50.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img50",coordinateValue);
		imgx = img51.x.toString();
		imgy = img51.y.toString();
		imgw = img51.w.toString();
		imgh = img51.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img51",coordinateValue);
		imgx = img52.x.toString();
		imgy = img52.y.toString();
		imgw = img52.w.toString();
		imgh = img52.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img52",coordinateValue);
		imgx = img53.x.toString();
		imgy = img53.y.toString();
		imgw = img53.w.toString();
		imgh = img53.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img53",coordinateValue);
		imgx = img54.x.toString();
		imgy = img54.y.toString();
		imgw = img54.w.toString();
		imgh = img54.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img54",coordinateValue);
		imgx = img55.x.toString();
		imgy = img55.y.toString();
		imgw = img55.w.toString();
		imgh = img55.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img55",coordinateValue);
		imgx = img56.x.toString();
		imgy = img56.y.toString();
		imgw = img56.w.toString();
		imgh = img56.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img56",coordinateValue);
		imgx = img57.x.toString();
		imgy = img57.y.toString();
		imgw = img57.w.toString();
		imgh = img57.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img57",coordinateValue);
		imgx = img58.x.toString();
		imgy = img58.y.toString();
		imgw = img58.w.toString();
		imgh = img58.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img58",coordinateValue);
		imgx = img59.x.toString();
		imgy = img59.y.toString();
		imgw = img59.w.toString();
		imgh = img59.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img59",coordinateValue);
		imgx = img60.x.toString();
		imgy = img60.y.toString();
		imgw = img60.w.toString();
		imgh = img60.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img60",coordinateValue);
		imgx = img61.x.toString();
		imgy = img61.y.toString();
		imgw = img61.w.toString();
		imgh = img61.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img61",coordinateValue);
		imgx = img62.x.toString();
		imgy = img62.y.toString();
		imgw = img62.w.toString();
		imgh = img62.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img62",coordinateValue);
		imgx = img63.x.toString();
		imgy = img63.y.toString();
		imgw = img63.w.toString();
		imgh = img63.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img63",coordinateValue);
		imgx = img64.x.toString();
		imgy = img64.y.toString();
		imgw = img64.w.toString();
		imgh = img64.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img64",coordinateValue);
		imgx = img65.x.toString();
		imgy = img65.y.toString();
		imgw = img65.w.toString();
		imgh = img65.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img65",coordinateValue);
		imgx = img66.x.toString();
		imgy = img66.y.toString();
		imgw = img66.w.toString();
		imgh = img66.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img66",coordinateValue);
		imgx = img67.x.toString();
		imgy = img67.y.toString();
		imgw = img67.w.toString();
		imgh = img67.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img67",coordinateValue);
		imgx = img68.x.toString();
		imgy = img68.y.toString();
		imgw = img68.w.toString();
		imgh = img68.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img68",coordinateValue);
		imgx = img69.x.toString();
		imgy = img69.y.toString();
		imgw = img69.w.toString();
		imgh = img69.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img69",coordinateValue);
		imgx = img70.x.toString();
		imgy = img70.y.toString();
		imgw = img70.w.toString();
		imgh = img70.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img70",coordinateValue);
		imgx = img71.x.toString();
		imgy = img71.y.toString();
		imgw = img71.w.toString();
		imgh = img71.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img71",coordinateValue);
		imgx = img72.x.toString();
		imgy = img72.y.toString();
		imgw = img72.w.toString();
		imgh = img72.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img72",coordinateValue);
		imgx = img73.x.toString();
		imgy = img73.y.toString();
		imgw = img73.w.toString();
		imgh = img73.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img73",coordinateValue);
		imgx = img74.x.toString();
		imgy = img74.y.toString();
		imgw = img74.w.toString();
		imgh = img74.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img74",coordinateValue);
		imgx = img75.x.toString();
		imgy = img75.y.toString();
		imgw = img75.w.toString();
		imgh = img75.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img75",coordinateValue);
		imgx = img76.x.toString();
		imgy = img76.y.toString();
		imgw = img76.w.toString();
		imgh = img76.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img76",coordinateValue);
		imgx = img77.x.toString();
		imgy = img77.y.toString();
		imgw = img77.w.toString();
		imgh = img77.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img77",coordinateValue);
		imgx = img78.x.toString();
		imgy = img78.y.toString();
		imgw = img78.w.toString();
		imgh = img78.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img78",coordinateValue);
		imgx = img79.x.toString();
		imgy = img79.y.toString();
		imgw = img79.w.toString();
		imgh = img79.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img79",coordinateValue);
		imgx = img80.x.toString();
		imgy = img80.y.toString();
		imgw = img80.w.toString();
		imgh = img80.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img80",coordinateValue);
		imgx = img81.x.toString();
		imgy = img81.y.toString();
		imgw = img81.w.toString();
		imgh = img81.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img81",coordinateValue);
		imgx = img82.x.toString();
		imgy = img82.y.toString();
		imgw = img82.w.toString();
		imgh = img82.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img82",coordinateValue);
		imgx = img83.x.toString();
		imgy = img83.y.toString();
		imgw = img83.w.toString();
		imgh = img83.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img83",coordinateValue);
		imgx = img84.x.toString();
		imgy = img84.y.toString();
		imgw = img84.w.toString();
		imgh = img84.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img84",coordinateValue);
		imgx = img85.x.toString();
		imgy = img85.y.toString();
		imgw = img85.w.toString();
		imgh = img85.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img85",coordinateValue);
		imgx = img86.x.toString();
		imgy = img86.y.toString();
		imgw = img86.w.toString();
		imgh = img86.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img86",coordinateValue);
		imgx = img87.x.toString();
		imgy = img87.y.toString();
		imgw = img87.w.toString();
		imgh = img87.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img87",coordinateValue);
		imgx = img88.x.toString();
		imgy = img88.y.toString();
		imgw = img88.w.toString();
		imgh = img88.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img88",coordinateValue);
		imgx = img89.x.toString();
		imgy = img89.y.toString();
		imgw = img89.w.toString();
		imgh = img89.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img89",coordinateValue);
		imgx = img90.x.toString();
		imgy = img90.y.toString();
		imgw = img90.w.toString();
		imgh = img90.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img90",coordinateValue);
		imgx = img91.x.toString();
		imgy = img91.y.toString();
		imgw = img91.w.toString();
		imgh = img91.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img91",coordinateValue);
		imgx = img92.x.toString();
		imgy = img92.y.toString();
		imgw = img92.w.toString();
		imgh = img92.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img92",coordinateValue);
		imgx = img93.x.toString();
		imgy = img93.y.toString();
		imgw = img93.w.toString();
		imgh = img93.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img93",coordinateValue);
		imgx = img94.x.toString();
		imgy = img94.y.toString();
		imgw = img94.w.toString();
		imgh = img94.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img94",coordinateValue);
		imgx = img95.x.toString();
		imgy = img95.y.toString();
		imgw = img95.w.toString();
		imgh = img95.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img95",coordinateValue);
		imgx = img96.x.toString();
		imgy = img96.y.toString();
		imgw = img96.w.toString();
		imgh = img96.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img96",coordinateValue);
		imgx = img97.x.toString();
		imgy = img97.y.toString();
		imgw = img97.w.toString();
		imgh = img97.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img97",coordinateValue);
		imgx = img98.x.toString();
		imgy = img98.y.toString();
		imgw = img98.w.toString();
		imgh = img98.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img98",coordinateValue);
		imgx = img99.x.toString();
		imgy = img99.y.toString();
		imgw = img99.w.toString();
		imgh = img99.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img99",coordinateValue);
		imgx = img100.x.toString();
		imgy = img100.y.toString();
		imgw = img100.w.toString();
		imgh = img100.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img100",coordinateValue);
		imgx = img101.x.toString();
		imgy = img101.y.toString();
		imgw = img101.w.toString();
		imgh = img101.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img101",coordinateValue);
		imgx = img102.x.toString();
		imgy = img102.y.toString();
		imgw = img102.w.toString();
		imgh = img102.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img102",coordinateValue);
		imgx = img103.x.toString();
		imgy = img103.y.toString();
		imgw = img103.w.toString();
		imgh = img103.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img103",coordinateValue);
		imgx = img104.x.toString();
		imgy = img104.y.toString();
		imgw = img104.w.toString();
		imgh = img104.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img104",coordinateValue);
		imgx = img105.x.toString();
		imgy = img105.y.toString();
		imgw = img105.w.toString();
		imgh = img105.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img105",coordinateValue);
		imgx = img106.x.toString();
		imgy = img106.y.toString();
		imgw = img106.w.toString();
		imgh = img106.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img106",coordinateValue);
		imgx = img107.x.toString();
		imgy = img107.y.toString();
		imgw = img107.w.toString();
		imgh = img107.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img107",coordinateValue);
		imgx = img108.x.toString();
		imgy = img108.y.toString();
		imgw = img108.w.toString();
		imgh = img108.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img108",coordinateValue);
		imgx = img109.x.toString();
		imgy = img109.y.toString();
		imgw = img109.w.toString();
		imgh = img109.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img109",coordinateValue);
		imgx = img110.x.toString();
		imgy = img110.y.toString();
		imgw = img110.w.toString();
		imgh = img110.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img110",coordinateValue);
		imgx = img111.x.toString();
		imgy = img111.y.toString();
		imgw = img111.w.toString();
		imgh = img111.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img111",coordinateValue);
		imgx = img112.x.toString();
		imgy = img112.y.toString();
		imgw = img112.w.toString();
		imgh = img112.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img112",coordinateValue);
		imgx = img113.x.toString();
		imgy = img113.y.toString();
		imgw = img113.w.toString();
		imgh = img113.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img113",coordinateValue);
		imgx = img114.x.toString();
		imgy = img114.y.toString();
		imgw = img114.w.toString();
		imgh = img114.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img114",coordinateValue);
		imgx = img115.x.toString();
		imgy = img115.y.toString();
		imgw = img115.w.toString();
		imgh = img115.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img115",coordinateValue);
		imgx = img116.x.toString();
		imgy = img116.y.toString();
		imgw = img116.w.toString();
		imgh = img116.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img116",coordinateValue);
		imgx = img117.x.toString();
		imgy = img117.y.toString();
		imgw = img117.w.toString();
		imgh = img117.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img117",coordinateValue);
		imgx = img118.x.toString();
		imgy = img118.y.toString();
		imgw = img118.w.toString();
		imgh = img118.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img118",coordinateValue);
		imgx = img119.x.toString();
		imgy = img119.y.toString();
		imgw = img119.w.toString();
		imgh = img119.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img119",coordinateValue);
		imgx = img120.x.toString();
		imgy = img120.y.toString();
		imgw = img120.w.toString();
		imgh = img120.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img120",coordinateValue);
		imgx = img121.x.toString();
		imgy = img121.y.toString();
		imgw = img121.w.toString();
		imgh = img121.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img121",coordinateValue);
		imgx = img122.x.toString();
		imgy = img122.y.toString();
		imgw = img122.w.toString();
		imgh = img122.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img122",coordinateValue);
		imgx = img123.x.toString();
		imgy = img123.y.toString();
		imgw = img123.w.toString();
		imgh = img123.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img123",coordinateValue);
		imgx = img124.x.toString();
		imgy = img124.y.toString();
		imgw = img124.w.toString();
		imgh = img124.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img124",coordinateValue);
		imgx = img125.x.toString();
		imgy = img125.y.toString();
		imgw = img125.w.toString();
		imgh = img125.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img125",coordinateValue);
		imgx = img126.x.toString();
		imgy = img126.y.toString();
		imgw = img126.w.toString();
		imgh = img126.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img126",coordinateValue);
		imgx = img127.x.toString();
		imgy = img127.y.toString();
		imgw = img127.w.toString();
		imgh = img127.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img127",coordinateValue);
		imgx = img128.x.toString();
		imgy = img128.y.toString();
		imgw = img128.w.toString();
		imgh = img128.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img128",coordinateValue);
		imgx = img129.x.toString();
		imgy = img129.y.toString();
		imgw = img129.w.toString();
		imgh = img129.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img129",coordinateValue);
		imgx = img130.x.toString();
		imgy = img130.y.toString();
		imgw = img130.w.toString();
		imgh = img130.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img130",coordinateValue);
		imgx = img131.x.toString();
		imgy = img131.y.toString();
		imgw = img131.w.toString();
		imgh = img131.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img131",coordinateValue);
		imgx = img132.x.toString();
		imgy = img132.y.toString();
		imgw = img132.w.toString();
		imgh = img132.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img132",coordinateValue);
		imgx = img133.x.toString();
		imgy = img133.y.toString();
		imgw = img133.w.toString();
		imgh = img133.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img133",coordinateValue);
		imgx = img134.x.toString();
		imgy = img134.y.toString();
		imgw = img134.w.toString();
		imgh = img134.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img134",coordinateValue);
		imgx = img135.x.toString();
		imgy = img135.y.toString();
		imgw = img135.w.toString();
		imgh = img135.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img135",coordinateValue);
		imgx = img136.x.toString();
		imgy = img136.y.toString();
		imgw = img136.w.toString();
		imgh = img136.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img136",coordinateValue);
		imgx = img137.x.toString();
		imgy = img137.y.toString();
		imgw = img137.w.toString();
		imgh = img137.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img137",coordinateValue);
		imgx = img138.x.toString();
		imgy = img138.y.toString();
		imgw = img138.w.toString();
		imgh = img138.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img138",coordinateValue);
		imgx = img139.x.toString();
		imgy = img139.y.toString();
		imgw = img139.w.toString();
		imgh = img139.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img139",coordinateValue);
		imgx = img140.x.toString();
		imgy = img140.y.toString();
		imgw = img140.w.toString();
		imgh = img140.h.toString();
		coordinateValue = imgx + "," +imgy + "," + imgw + "," + imgh;
		localStorage.setItem("img140",coordinateValue);

		window.alert("game saved!");
	} 
	else {
	    window.alert("Sorry! No Web Storage support..");
	}
});

//load button 
loadB.bind("Click", function(e){

	if(typeof(Storage) !== "undefined") {

		if (localStorage.img1!== null) {
		var pair = localStorage.getItem("img1");
		var coords = pair.split(",");
		img1.attr({x:cardWidth+170, y:5, w:cardWidth,h: cardHeight})
			.bind("Click", function(e) {
				if(!dragging){
					this.attr({x:this._x, y:this._y, w:cardWidth+200,h: cardHeight+200});
					this.z = 3;
				}
			})
			.bind("MouseOut", function(e) {
				if(!dragging){
					this.attr({x:this._x, y:this._y, w:cardWidth,h: cardHeight});
					this.z=2;
				}
			})
			.bind("DoubleClick", function(e){
				var j = onTopPickPileN.indexOf(this);
				if(j >= 0){
					onTopPickPileN.splice(j,1);
				}
				if(j >=0){
					stackN.push(this);		
				}
				this.attr({x:800, y:500, w:0,h: 0});
				if(stackN.length > 0){
					imgNB.attr({x:0, y:0, w: cardWidth, h:cardHeight});
				}
			})
			.bind("StartDrag", function(e){
				dragging = true;
			})				
			.bind("StopDrag", function(e){
				dragging = false;
				if(checkContained(this._x,this._y)){
					var coordinates = coordinatesContained(this._x,this._y);
					this.attr({x:coordinates.x-5,y:coordinates.y+5,w:cardWidth,h:cardHeight});	
				}
			});
		img1.z = 2;
		if (img1.h!==0) {
		 stackN.splice(j,1);
		 onTopPickPileN.push(img1);}
		}


		window.alert("game loaded!");		
	} 
	else {
	    window.alert("Sorry! No Web Storage support..");
	}
});



